export const UPDATE_POSTS = 'UPDATE_POSTS';

// Auth Action Types
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOG_OUT = 'LOG_OUT';

export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const GET_USER_WITH_ID = 'GET_USER_WITH_ID';
export const GET_USER_WITH_ID_SUCCESS = 'GET_USER_WITH_ID_SUCCESS';
export const GET_USER_WITH_ID_FAIL = 'GET_USER_WITH_ID_FAIL';

export const FETCH_FRIEND_SUCCESS = 'FETCH_FRIEND_SUCCESS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';

export const ADD_POST = 'ADD_POST';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const UPDATE_POST_LIKE = 'UPDATE_POST_LIKE';
export const FETCH_SEARCH_RESULT_SUCCESS = 'FETCH_SEARCH_RESULT_SUCCESS';
